### ISSUE TITLE
真机测试 没生效

### ISSUE THREAD

**Issue by martinholly** [internetWei/LLDynamicLaunchScreen#1]
使用情况如下:在iOS14或者iOS13及以下系统中 项目的启动图是LaunchScreen.storyboard中放一张全屏的png图片,  APP使用三天后(大概3天 - 5天)就会出现这张图片变成黑色的情况(可能因为缓存问题), 然后在代码中执行了[LLDynamicLaunchScreen restoreAsBefore]代码之后 重新运行 没有生效 还是黑色

**Comment by internetWei** [comment]
如果您还未解决问题的话可以联系我，Demo上修复启动图成功的Gif图，您可以参考一下。

**Comment by internetWei** [comment]
```objc
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    
    self.window = [[UIWindow alloc] initWithFrame:UIScreen.mainScreen.bounds];
    
    [LLDynamicLaunchScreen restoreAsBefore];
    return YES;
}
```
参考以上代码即可修复启动图变成黑色的问题PS([LLDynamicLaunchScreen restoreAsBefore];一定要放在window初始化后执行)。

重新运行⌘+R，无论是运行在模拟器上还是真机上，系统都会重新生成启动图。这样的话LLDynamicLaunchScreen之前替换过的图片就失效了。用户使用APP时系统是不会反复生成启动图，只在首次安装APP和更新APP后才会生成启动图。所以你只需要把[LLDynamicLaunchScreen restoreAsBefore];放在window初始化后执行即可，如果运行后启动图还是黑屏，请打包到蒲公英下载测试。
