### ISSUE TITLE
没有动态更换启动图需求，是否接入框架？

### ISSUE THREAD

**Issue by GKWenBo** [internetWei/LLDynamicLaunchScreen#16]
作者，你好，最近项目在更换启动图为launchscreen，请教一个问题，如果不使用动态替换，是否会出现启动图异常问题呢

**Comment by internetWei** [comment]
我第1次发现启动图显示异常已经是2年前了，最近这几年在真机上发现启动图显示异常的情况少了很多，如果你不想集成的话可以不使用该框架，应该也不会出现启动图显示异常，如果真的出现了，那等出现了再集成也行。

如果你是因为不清楚框架内部逻辑而不放心使用的话，在这里我可以简单的像你介绍一下：框架会在每次启动时判断是不是首次启动(`下载后和更新后首次打开均算`)，如果是首次启动则开始检查本地的启动图内容，检查的逻辑就是对LaunchScreen.storyboard中UIImageView的显示区域进行截图，然后对本地启动图进行同样的截图，拿2张截图进行比较，理论上来说这2张图片应该是一样的，如果出现了不一样则认为启动图显示异常，此时才会自动修复异常的启动图；上面说的操作只有第1个检查是不是首次启动是在当前线程进行的，其他逻辑均是在子线程中进行，所以你不用担心会影响主线程卡顿。

我的建议是如果你目前不需要的话可以不集成，等发生了再集成都可以。

**Comment by GKWenBo** [comment]
谢谢您耐心的解答，后面如有需要，一定支持作者框架
