### ISSUE TITLE
有试过iOS16.4吗？

### ISSUE THREAD

**Issue by codeguesser** [internetWei/LLDynamicLaunchScreen#17]
Version 14.3 (14E222b)
模拟器iOS16.4
目前不起作用。直接下载demo直接测试，无效。

**Comment by internetWei** [comment]
当然试过，README中的demo就是在真机iPhone 14，iOS 16.4.1 上录制的；我又尝试了一遍使用 iPhone 14 Pro ，iOS 16.4 模拟器进行测试，没有发现你的问题，请看下图demo:

![demo](https://github.com/internetWei/LLDynamicLaunchScreen/assets/55784556/f2a64dc9-4d44-4cb4-ab73-9f89f176bb7f)

你测试的时候，修改完启动图是重新运行项目了吗？如果是的话请不要重新运行，每次运行后系统都会重新生成一份启动图，你也不用担忧这种问题，因为用户在iPhone上使用APP时是无法重新运行的，如果不是我说的这样的话请继续联系我，如果你能提供视图或其它复现步骤的话能帮我更快排查问题。

**Comment by codeguesser** [comment]
多谢大佬解惑，确实可以
