### ISSUE TITLE
APP重新下载后，修改启动图不成功，都是默认图，定位不到原因

### ISSUE THREAD

**Issue by lewis180777** [internetWei/LLDynamicLaunchScreen#2]
APP重新下载后，修改启动图不成功，都是默认图，定位不到原因

**Comment by internetWei** [comment]
您的意思是首次下载后修改是正常的，重新下载后就修改不成功了吗？可以详细描述一个您的测试流程吗？或者把您的工程压缩后发到我的邮箱也可以。

**Comment by lewis180777** [comment]
> 您的意思是首次下载后修改是正常的，重新下载后就修改不成功了吗？可以详细描述一个您的测试流程吗？或者把您的工程压缩后发到我的邮箱也可以。

对，重新下载修改，打印log是修改成功了，就是启动图是默认的。我就是直接用你的工程测试的，你可以打个包发布蒲公英，下载安装，修改后验证是否成功，然后再重新安装一次，就怎么修改都改不了启动图

**Comment by internetWei** [comment]
重新安装前卸载之前的APP了吗？

**Comment by lewis180777** [comment]
> 重新安装前卸载之前的APP了吗？

肯定不卸载啊！你更新APP会叫用户卸载重装吗？
是不是重装后的路径不一样了？
我发现你的代码跟这个差不多https://github.com/iversonxh/DynamicLaunchImage，这个仓库的没有这个问题

**Comment by internetWei** [comment]
问题出在你从蒲公英更新的时候版本号没有发生改变。而用户更新的话版本号肯定会发生变化。
LLDynamicLaunchScreen内部做了优化，不会在每次启动时都生成。

```objc
// 判断是否需要重新初始化启动图资源
    if ([app_version isEqualToString:old_app_version] &&
        ![self isEmptyDir:localPath]) return;
```

代码里有这么一个逻辑，会判断版本号是否和上次记录的不一致以及本地是否存在缓存。如果版本号不一致或者本地没有缓存则会去重新生成一些必要信息。

您可以增加版本号，然后上传至蒲公英再更新试试。

**Comment by internetWei** [comment]
您提到的`DynamicLaunchImage`，我在测试它的过程中发现有1个很严重的问题，当我在1.0版本修改了启动图然后更新到1.1版本后启动图会丢失，而且它已经很久没有提交了(可能也不会维护了)。另外它的功能也没有`LLDynamicLaunchScreen`强大，建议您不要使用`DynamicLaunchImage`而是使用`LLDynamicLaunchScreen`。
