### ISSUE TITLE
iOS17中UIGraphicsBeginImageContextWithOptions已经deprecated

### ISSUE THREAD

**Issue by EchoLunar** [internetWei/LLDynamicLaunchScreen#25]
![image](https://github.com/internetWei/LLDynamicLaunchScreen/assets/36027902/b34984e4-1a57-4bc6-bd1c-622a5b3230b3)
UIGraphicsBeginImageContextWithOptions这个方法在iOS17中已经deprecated了，但是项目中有多处使用了这个方法，我在其他三方库中发现不少作者已经移除了这个方法,并使用了UIGraphicsImageRenderer来代替。
![image](https://github.com/internetWei/LLDynamicLaunchScreen/assets/36027902/0507c699-b443-4f4f-bb91-5e2b641cd131)
不知道作者是否注意到这个问题。

**Comment by internetWei** [comment]
正在改

**Comment by internetWei** [comment]
最新版本 1.0.7 已适配
