### ISSUE TITLE
启动图更换成功，但是每次打开app的时候会闪原来的图

### ISSUE THREAD

**Issue by vayneee** [internetWei/LLDynamicLaunchScreen#29]
启动图更换成功，但是每次打开app的时候会先展示新的图，再闪一下原来的图。

**Comment by internetWei** [comment]
你在有问题的手机上试一下项目中的 Demo，看看是否也有此问题。
如果方便的话麻烦你发一下有问题项目的Demo。

**Comment by vayneee** [comment]
您的demo没有问题。 一开始我这边也是会闪一下。 后来我对比demo，我在General->App Icons and Launch Screen -> Launch Screen File 选中LaunchScreen.storyboard 就可以了。我合并代码之后，其他人的项目都跑不起来了，会提示Could not find a storyboard named 'LaunchScreen.storyboard' in bundle TUIBundle 这个错误。 然后他们在info里把Launch screen interface file base name里的.storyboard 去掉项目可以正常运行。但是会出现新图后闪一下原来的图。 我发现您的demo这里不配置也可以生效。我不太明白是哪里出的问题。

**Comment by vayneee** [comment]
我又尝试了新创建的工程也是会闪一下。

**Comment by internetWei** [comment]
您好，我用1台 iOS 18 的 iPhone 14设备运行了线上最新的代码，没有发现您说的会闪一下的问题。麻烦您提供一下测试机型的手机型号、版本号、测试视频等相关信息。最好能提供一份有问题的项目代码，这样我能更快的解决您提到的问题。

**Comment by vayneee** [comment]
找到问题，是我们使用的广告的SDK导致的。
