### ISSUE TITLE
ios 13以下的开屏截图Snapshots路径，在真机下权限是不可读、不可写的，请问是怎么做到也可以修改的？

### ISSUE THREAD

**Issue by code1303009** [internetWei/LLDynamicLaunchScreen#3]

**Comment by internetWei** [comment]
您好，iOS13以下系统的启动图路径在真机下确实是无法读取也无法写入的。
但是moveItem:这个方法可以将启动图文件夹移动到其他位置，修改好以后再通过moveItem:移动到原先的位置。这样就变相的达到了读取和写入的目的。
为了实现这个功能尝试到几乎要放弃，如果您认可我的话麻烦点个Star吧，感谢🙏。


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: Martin.J <notifications@github.com&gt;
发送时间: 2021年1月9日 16:33
收件人: internetWei/LLDynamicLaunchScreen <LLDynamicLaunchScreen@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[internetWei/LLDynamicLaunchScreen] ios 13以下的开屏截图Snapshots路径，在真机下权限是不可读、不可写的，请问是怎么做到也可以修改的？ (#3)

**Comment by code1303009** [comment]
恩恩 
好的 我去试下

**Comment by code1303009** [comment]
尝试了下，虽然13以下SnapShot权限不可操作，但是Cache同目录下文件移动还是可以的👍
