### ISSUE TITLE
更新应用后第一次启动还是原先缓存图片

### ISSUE THREAD

**Issue by dingxiaoliu** [internetWei/LLDynamicLaunchScreen#5]
更新应用后是不是第一次启动的时候还是加载原先缓存图片，只有第二次以后启动APP才会显示新的启动图？

**Comment by dingxiaoliu** [comment]
方便加个QQ或者微信吗？有时候我发现真机缓存里有2张启动图片，导致一直加载的是原来的启动图

**Comment by dingxiaoliu** [comment]
1137303424，这个是我的QQ

**Comment by internetWei** [comment]
可以。w1921202322，这是我的微信号


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: dingxiaoliu <notifications@github.com&gt;
发送时间: 2021年1月15日 12:17
收件人: internetWei/LLDynamicLaunchScreen <LLDynamicLaunchScreen@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[internetWei/LLDynamicLaunchScreen] 更新应用后第一次启动还是原先缓存图片 (#5)





 
方便加个QQ或者微信吗？有时候我发现真机缓存里有2张启动图片，导致一直加载的是原来的启动图

**Comment by internetWei** [comment]
您好，您提的问题最新版本已修复；请及时更新版本，感谢您的反馈。
