### ISSUE TITLE
测试发现 只能更换三张图片

### ISSUE THREAD

**Issue by to-explore-future** [internetWei/LLDynamicLaunchScreen#6]
您好，我用模拟器测试一下你写的demo，连续更换三张图片没问题，到第四张图片就没反应了，重新启动的时候还是第三张图片，我看看一下缓存路径的图片是改变了，但是启动的时候，并没有加载出来，

**Comment by internetWei** [comment]
您好，我不太明白您说的意思，请详细描述一下您遇到的问题，如果有图片或Gif图的话可能会更好。

另外，修改启动图后不要重新⌘R重新运行工程，可以手动退出APP然后打开查看效果。⌘R重新运行工程的话系统会重新生成一套启动图而不会使用本地的启动图。用户在使用的时候是不会重新生成启动图的(除非更新版本，这种情况已经做过处理了，用户更新版本后第一次打开会看到默认启动图(这是系统限制，暂时无法解决)，但是后续每次打开都会是之前设置的启动图)。

**Comment by to-explore-future** [comment]
您好，我录了个视频，[视频地址](https://zqtemp.oss-cn-beijing.aliyuncs.com/%E5%B1%8F%E5%B9%95%E5%BD%95%E5%88%B62021-03-10%2017.00.05.mov) ，当我连续切换到第四张图片的时候，开屏图片就变成黑屏，有的时候回停留在第三张图片 我用模拟器测试的，    
您看看我发现的问题能够复现吗 ，我用模拟器测试

**Comment by internetWei** [comment]
写在前面的话：
    您视频中的问题只会在模拟器中发生，用户下载APP使用的话是不会发生的。问题出现的原因如下：
    `LLDynamicLaunchScreen`会在程序运行以后遍历系统的启动图文件夹，然后将这些启动图的名称与它们的类型一一对应并保存到本地。正常情况下这个操作只会在用户首次安装APP和更新APP后第一次打开时发生。但是在模拟器中每次运行APP时系统都会重新生成一套启动图(下载的APP不会)，所以我在内部加了判断如果当前环境是模拟器的话，每次运行APP时都会触发逻辑重新记录启动图的名称并存储到本地。

```
     默认情况下，`LLaunchScreen`通过获取图片最右上角1×1像素单位的RGB值来判断该图片是不是暗黑系图片；
     如果您需要修改它，请在`application: didFinishLaunchingWithOptions:`返回前实现它。
```

  上面这段注释你可以在工程中找到。问题就出在你替换的第4张图片的最右上角1×1像素单位的RGB值被误判成了是暗黑启动图，但其实它是浅色启动图，这就导致启动图名称的映射字典中少了一条`浅色竖屏启动图`的记录，以致于你在后面每次替换`浅色竖屏启动图`时都因为找不以对应的启动图名称而替换失败，所以你每次打开APP时显示的一直是第4次设置的启动图。
    
  最后：如果用户是通过下载(App Store或者蒲公英等分发下载都算)APP后修改启动图的话，只会在每次更新版本后第一次打开APP时才会重新记录启动图的名称映射字典。如果您APP中默认的浅色启动图和深色启动图的右上角1×1像素点RGB值很相似的话可能会发生这样的问题。但是你可以通过`hasDarkImageBlock`这个属性来解决这个问题。

**Comment by to-explore-future** [comment]
奥 明白了 非常感谢
